# Generated by Django 2.2.6 on 2019-11-06 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191107_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='students.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Program'),
        ),
    ]
