# Generated by Django 2.2.6 on 2019-11-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191107_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='program',
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ManyToManyField(blank=True, null=True, to='students.Program'),
        ),
    ]
